/**
 * VYRON — AUTHORITATIVE NORMALIZED CONNECTOR CATALOG (GOD MODE vNEXT)
 * Directives: 703-793, 1558-1577, 2306-2310
 *
 * Normalizes 70+ external connectors preserving provider names, categories,
 * status badges (Trending, Beta, New, Community, Certified), required scopes,
 * capability contracts, and auth protocols.
 *
 * Zero secrets in frontend. Zero tokens exposed to Copilot LLM.
 * Strictly ZERO SQL.
 */

export type ConnectorCategory =
  | "Productivity"
  | "Design & Creative"
  | "Engineering & DevOps"
  | "AI & Research"
  | "Business & CRM"
  | "Finance & Commerce"
  | "Communication"
  | "Storage & Documents";

export type ConnectorBadgeStatus = "Trending" | "Beta" | "New" | "Community" | "Certified";

export type ConnectorAuthType = "OAuth 2.0" | "API Key" | "MCP Native" | "Service Token";

export interface NormalizedConnectorDef {
  id: string;
  name: string;
  provider: string;
  category: ConnectorCategory;
  description: string;
  sourceUrl: string;
  iconName: string;
  statusBadge: ConnectorBadgeStatus;
  capabilitySummary: string;
  authType: ConnectorAuthType;
  scopes: string[];
  toolsProvided: string[];
  popularityScore: number; // 0 to 100
  isConnected: boolean;
  healthState:
    | "CONNECTED"
    | "HEALTHY"
    | "DEGRADED"
    | "AUTH_EXPIRED"
    | "PERMISSION_DENIED"
    | "RATE_LIMITED"
    | "PROVIDER_ERROR"
    | "DISCONNECTED"
    | "UNKNOWN";
  lastSyncedAt?: string;
}

export const AUTHORITATIVE_CONNECTOR_CATALOG: NormalizedConnectorDef[] = [
  // --- Productivity & Workspace ---
  {
    id: "google_drive",
    name: "Google Drive",
    provider: "Google LLC",
    category: "Storage & Documents",
    description: "Search, retrieve, and inspect architecture documents, blueprints, and data exports.",
    sourceUrl: "https://workspace.google.com/products/drive/",
    iconName: "HardDrive",
    statusBadge: "Trending",
    capabilitySummary: "File retrieval, folder tree inspection, PDF & sheet text extraction.",
    authType: "OAuth 2.0",
    scopes: ["drive.readonly", "drive.metadata.readonly"],
    toolsProvided: ["google_drive_search", "google_drive_read"],
    popularityScore: 99,
    isConnected: true,
    healthState: "HEALTHY",
  },
  {
    id: "gmail",
    name: "Gmail",
    provider: "Google LLC",
    category: "Communication",
    description: "Inspect project correspondence, alert notifications, and deployment announcements.",
    sourceUrl: "https://workspace.google.com/products/gmail/",
    iconName: "Mail",
    statusBadge: "Certified",
    capabilitySummary: "Thread search, sender verification, alert filtering.",
    authType: "OAuth 2.0",
    scopes: ["gmail.readonly"],
    toolsProvided: ["gmail_search_threads", "gmail_read_message"],
    popularityScore: 94,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
  {
    id: "google_calendar",
    name: "Google Calendar",
    provider: "Google LLC",
    category: "Productivity",
    description: "Synchronize architecture reviews, release freezes, and incident on-call schedules.",
    sourceUrl: "https://workspace.google.com/products/calendar/",
    iconName: "Calendar",
    statusBadge: "Certified",
    capabilitySummary: "Schedule inspection, freeze window detection, meeting participant sync.",
    authType: "OAuth 2.0",
    scopes: ["calendar.readonly", "calendar.events.readonly"],
    toolsProvided: ["calendar_list_events", "calendar_check_freeze"],
    popularityScore: 92,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
  {
    id: "microsoft_365",
    name: "Microsoft 365",
    provider: "Microsoft Corp",
    category: "Productivity",
    description: "Enterprise SharePoint, OneDrive, and Outlook document and message ingestion.",
    sourceUrl: "https://www.microsoft.com/microsoft-365",
    iconName: "Briefcase",
    statusBadge: "Certified",
    capabilitySummary: "SharePoint doc search, OneDrive sync, Exchange message retrieval.",
    authType: "OAuth 2.0",
    scopes: ["Files.Read.All", "Mail.Read"],
    toolsProvided: ["m365_search_files", "m365_read_doc"],
    popularityScore: 91,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
  {
    id: "notion",
    name: "Notion",
    provider: "Notion Labs",
    category: "Productivity",
    description: "Engineering wikis, Architecture Decision Records (ADR), and team sprint databases.",
    sourceUrl: "https://www.notion.so",
    iconName: "FileText",
    statusBadge: "Trending",
    capabilitySummary: "Page query, block extraction, database property filtering.",
    authType: "OAuth 2.0",
    scopes: ["pages:read", "databases:read"],
    toolsProvided: ["notion_search_pages", "notion_read_page"],
    popularityScore: 97,
    isConnected: true,
    healthState: "HEALTHY",
  },
  {
    id: "slack",
    name: "Slack",
    provider: "Salesforce / Slack",
    category: "Communication",
    description: "Channel monitoring, incident war room alerts, and automated release notifications.",
    sourceUrl: "https://slack.com",
    iconName: "MessageSquare",
    statusBadge: "Trending",
    capabilitySummary: "Channel reading, bot notification dispatch, thread search.",
    authType: "OAuth 2.0",
    scopes: ["channels:read", "chat:write"],
    toolsProvided: ["slack_read_channel", "slack_post_message"],
    popularityScore: 96,
    isConnected: true,
    healthState: "HEALTHY",
  },

  // --- Design & Creative ---
  {
    id: "figma",
    name: "Figma",
    provider: "Figma Inc",
    category: "Design & Creative",
    description: "Design system tokens, component schemas, wireframes, and UI canvas inspection.",
    sourceUrl: "https://www.figma.com",
    iconName: "Figma",
    statusBadge: "Trending",
    capabilitySummary: "Design token export, component tree inspection, frame comment search.",
    authType: "OAuth 2.0",
    scopes: ["files:read"],
    toolsProvided: ["figma_get_file_nodes", "figma_export_tokens"],
    popularityScore: 95,
    isConnected: true,
    healthState: "HEALTHY",
  },
  {
    id: "canva",
    name: "Canva",
    provider: "Canva Pty Ltd",
    category: "Design & Creative",
    description: "Visual assets, presentation decks, and technical marketing diagrams.",
    sourceUrl: "https://www.canva.com",
    iconName: "Palette",
    statusBadge: "New",
    capabilitySummary: "Asset retrieval, visual template search.",
    authType: "OAuth 2.0",
    scopes: ["asset:read"],
    toolsProvided: ["canva_search_designs"],
    popularityScore: 84,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
  {
    id: "miro",
    name: "Miro",
    provider: "RealtimeBoard Inc",
    category: "Design & Creative",
    description: "Collaborative system architecture whiteboards and user story mapping.",
    sourceUrl: "https://miro.com",
    iconName: "Layout",
    statusBadge: "Certified",
    capabilitySummary: "Board item extraction, sticky note search, diagram OCR.",
    authType: "OAuth 2.0",
    scopes: ["boards:read"],
    toolsProvided: ["miro_get_board"],
    popularityScore: 88,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
  {
    id: "adobe",
    name: "Adobe Creative Cloud",
    provider: "Adobe Inc",
    category: "Design & Creative",
    description: "Creative asset libraries, brand guidelines, and vector design standards.",
    sourceUrl: "https://www.adobe.com",
    iconName: "Image",
    statusBadge: "Certified",
    capabilitySummary: "Library sync, asset metadata search.",
    authType: "OAuth 2.0",
    scopes: ["creative_sdk:read"],
    toolsProvided: ["adobe_search_assets"],
    popularityScore: 82,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
  {
    id: "gamma",
    name: "Gamma",
    provider: "Gamma App Inc",
    category: "Design & Creative",
    description: "AI-generated executive documentation and engineering slide briefs.",
    sourceUrl: "https://gamma.app",
    iconName: "Monitor",
    statusBadge: "New",
    capabilitySummary: "Deck generation, brief export.",
    authType: "API Key",
    scopes: ["read", "write"],
    toolsProvided: ["gamma_export_deck"],
    popularityScore: 80,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
  {
    id: "excalidraw",
    name: "Excalidraw",
    provider: "Excalidraw OSS",
    category: "Design & Creative",
    description: "Hand-drawn architecture sketches, data flow diagrams, and ERD schematics.",
    sourceUrl: "https://excalidraw.com",
    iconName: "PenTool",
    statusBadge: "Community",
    capabilitySummary: "Scene JSON parsing, diagram element extraction.",
    authType: "MCP Native",
    scopes: ["read"],
    toolsProvided: ["excalidraw_parse_scene"],
    popularityScore: 89,
    isConnected: false,
    healthState: "DISCONNECTED",
  },

  // --- Engineering & DevOps ---
  {
    id: "github",
    name: "GitHub Enterprise",
    provider: "GitHub / Microsoft",
    category: "Engineering & DevOps",
    description: "Repository structural discovery, git blame metadata, PRs, and commit frequency.",
    sourceUrl: "https://github.com",
    iconName: "Github",
    statusBadge: "Trending",
    capabilitySummary: "Code tree inspection, commit history, issue tracker, PR checks.",
    authType: "OAuth 2.0",
    scopes: ["repo", "read:org", "read:user"],
    toolsProvided: ["github_get_repo_tree", "github_get_commits", "github_create_issue"],
    popularityScore: 100,
    isConnected: true,
    healthState: "HEALTHY",
  },
  {
    id: "supabase",
    name: "Supabase",
    provider: "Supabase Inc",
    category: "Engineering & DevOps",
    description: "PostgreSQL schema contracts, RLS security policies, and edge function telemetry.",
    sourceUrl: "https://supabase.com",
    iconName: "Database",
    statusBadge: "Trending",
    capabilitySummary: "Schema inspection, policy audit, migration tracking.",
    authType: "Service Token",
    scopes: ["schema:read", "metrics:read"],
    toolsProvided: ["supabase_inspect_schema", "supabase_audit_rls"],
    popularityScore: 98,
    isConnected: true,
    healthState: "HEALTHY",
  },
  {
    id: "linear",
    name: "Linear",
    provider: "Linear Orbit Inc",
    category: "Engineering & DevOps",
    description: "Issue tracking, cycle planning, sprint blocker isolation, and bug triage.",
    sourceUrl: "https://linear.app",
    iconName: "CheckSquare",
    statusBadge: "Trending",
    capabilitySummary: "Issue search, cycle progress audit, issue creation with idempotency.",
    authType: "OAuth 2.0",
    scopes: ["read", "write"],
    toolsProvided: ["linear_search_issues", "linear_create_issue"],
    popularityScore: 96,
    isConnected: true,
    healthState: "HEALTHY",
  },
  {
    id: "atlassian_rovo",
    name: "Atlassian Rovo & Jira",
    provider: "Atlassian Pty Ltd",
    category: "Engineering & DevOps",
    description: "Enterprise Jira project tracking, Confluence knowledge, and enterprise search.",
    sourceUrl: "https://www.atlassian.com/software/rovo",
    iconName: "Layers",
    statusBadge: "Trending",
    capabilitySummary: "Jira ticket search, Confluence page search, sprint blocker sync.",
    authType: "OAuth 2.0",
    scopes: ["read:jira-work", "read:confluence-content"],
    toolsProvided: ["jira_search_issues", "confluence_read_page"],
    popularityScore: 93,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
  {
    id: "asana",
    name: "Asana",
    provider: "Asana Inc",
    category: "Engineering & DevOps",
    description: "Task management, engineering milestones, and cross-team roadmap delivery.",
    sourceUrl: "https://asana.com",
    iconName: "CheckCircle",
    statusBadge: "Certified",
    capabilitySummary: "Project task search, milestone progress tracking.",
    authType: "OAuth 2.0",
    scopes: ["default"],
    toolsProvided: ["asana_list_tasks"],
    popularityScore: 86,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
  {
    id: "vercel",
    name: "Vercel",
    provider: "Vercel Inc",
    category: "Engineering & DevOps",
    description: "Edge deployment logs, preview URL verification, and build performance telemetry.",
    sourceUrl: "https://vercel.com",
    iconName: "Zap",
    statusBadge: "Trending",
    capabilitySummary: "Deployment status, runtime error logs, edge cache analytics.",
    authType: "OAuth 2.0",
    scopes: ["deployments:read"],
    toolsProvided: ["vercel_get_deployments", "vercel_get_logs"],
    popularityScore: 95,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
  {
    id: "datadog",
    name: "Datadog",
    provider: "Datadog Inc",
    category: "Engineering & DevOps",
    description: "Cloud observability, APM distributed tracing, metric alerts, and synthetic checks.",
    sourceUrl: "https://www.datadoghq.com",
    iconName: "Activity",
    statusBadge: "Trending",
    capabilitySummary: "Metric query, active monitor alerts, APM latency distribution.",
    authType: "API Key",
    scopes: ["monitors_read", "metrics_read"],
    toolsProvided: ["datadog_query_metrics", "datadog_get_monitors"],
    popularityScore: 94,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
  {
    id: "sentry",
    name: "Sentry",
    provider: "Functional Software Inc",
    category: "Engineering & DevOps",
    description: "Real-time error tracking, exception stack traces, and release regression alerts.",
    sourceUrl: "https://sentry.io",
    iconName: "AlertTriangle",
    statusBadge: "Trending",
    capabilitySummary: "Issue stream filtering, stack trace analysis, release regression checks.",
    authType: "OAuth 2.0",
    scopes: ["event:read", "project:read"],
    toolsProvided: ["sentry_get_issues", "sentry_inspect_trace"],
    popularityScore: 95,
    isConnected: true,
    healthState: "HEALTHY",
  },
  {
    id: "cloudflare_developer_platform",
    name: "Cloudflare Developer Platform",
    provider: "Cloudflare Inc",
    category: "Engineering & DevOps",
    description: "Workers, D1 SQLite databases, R2 object storage, and edge routing policies.",
    sourceUrl: "https://developers.cloudflare.com",
    iconName: "Cloud",
    statusBadge: "Trending",
    capabilitySummary: "Worker metrics, DNS audit, security firewall event streams.",
    authType: "API Key",
    scopes: ["workers:read", "analytics:read"],
    toolsProvided: ["cloudflare_get_worker_metrics"],
    popularityScore: 92,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
  {
    id: "netlify",
    name: "Netlify",
    provider: "Netlify Inc",
    category: "Engineering & DevOps",
    description: "Continuous deployment statuses, form analytics, and serverless functions.",
    sourceUrl: "https://www.netlify.com",
    iconName: "Globe",
    statusBadge: "Certified",
    capabilitySummary: "Site build status, deployment checks.",
    authType: "OAuth 2.0",
    scopes: ["read"],
    toolsProvided: ["netlify_get_deploys"],
    popularityScore: 85,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
  {
    id: "postman",
    name: "Postman",
    provider: "Postman Inc",
    category: "Engineering & DevOps",
    description: "API collection contracts, mock server endpoints, and OpenAPI schema specs.",
    sourceUrl: "https://www.postman.com",
    iconName: "Send",
    statusBadge: "Certified",
    capabilitySummary: "Collection inspection, schema validation, environment variable audit.",
    authType: "API Key",
    scopes: ["collections:read"],
    toolsProvided: ["postman_get_collections"],
    popularityScore: 91,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
  {
    id: "railway",
    name: "Railway",
    provider: "Railway App Inc",
    category: "Engineering & DevOps",
    description: "Container infrastructure, deployment logs, and microservice environment variables.",
    sourceUrl: "https://railway.app",
    iconName: "Server",
    statusBadge: "Trending",
    capabilitySummary: "Service health, deployment logs, variable validation.",
    authType: "API Key",
    scopes: ["project:read"],
    toolsProvided: ["railway_get_services"],
    popularityScore: 89,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
  {
    id: "snowflake",
    name: "Snowflake",
    provider: "Snowflake Inc",
    category: "Engineering & DevOps",
    description: "Enterprise data warehouse querying, warehouse compute telemetry, and governance.",
    sourceUrl: "https://www.snowflake.com",
    iconName: "Database",
    statusBadge: "Certified",
    capabilitySummary: "Warehouse query metrics, schema table search.",
    authType: "OAuth 2.0",
    scopes: ["session:read"],
    toolsProvided: ["snowflake_inspect_schema"],
    popularityScore: 92,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
  {
    id: "google_cloud_bigquery",
    name: "Google Cloud BigQuery",
    provider: "Google LLC",
    category: "Engineering & DevOps",
    description: "Serverless data analytics, partitioned table inspection, and SQL cost estimation.",
    sourceUrl: "https://cloud.google.com/bigquery",
    iconName: "Search",
    statusBadge: "Certified",
    capabilitySummary: "Dataset table inspection, partition query cost estimator.",
    authType: "OAuth 2.0",
    scopes: ["bigquery.readonly"],
    toolsProvided: ["bigquery_inspect_dataset"],
    popularityScore: 93,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
  {
    id: "replit",
    name: "Replit",
    provider: "Replit Inc",
    category: "Engineering & DevOps",
    description: "Cloud repl development workspaces, containerized environments, and deployments.",
    sourceUrl: "https://replit.com",
    iconName: "Terminal",
    statusBadge: "Community",
    capabilitySummary: "Repl status, deployment telemetry.",
    authType: "API Key",
    scopes: ["read"],
    toolsProvided: ["replit_get_repl_status"],
    popularityScore: 84,
    isConnected: false,
    healthState: "DISCONNECTED",
  },

  // --- AI & Research ---
  {
    id: "kaggle",
    name: "Kaggle Open Data",
    provider: "Kaggle / Google",
    category: "AI & Research",
    description: "Machine learning benchmarks, public dataset exploration, and schema verification.",
    sourceUrl: "https://www.kaggle.com",
    iconName: "Database",
    statusBadge: "Trending",
    capabilitySummary: "Dataset search, column contract evaluation, sample partition extraction.",
    authType: "MCP Native",
    scopes: ["datasets:read"],
    toolsProvided: ["kaggle_search_datasets", "kaggle_inspect_schema"],
    popularityScore: 95,
    isConnected: true,
    healthState: "HEALTHY",
  },
  {
    id: "hugging_face",
    name: "Hugging Face",
    provider: "Hugging Face Inc",
    category: "AI & Research",
    description: "Open-source model weights, dataset cards, Space telemetry, and evaluations.",
    sourceUrl: "https://huggingface.co",
    iconName: "Cpu",
    statusBadge: "Trending",
    capabilitySummary: "Model card search, dataset card inspection, Hub commit tracking.",
    authType: "API Key",
    scopes: ["read"],
    toolsProvided: ["hf_search_models", "hf_get_dataset_card"],
    popularityScore: 97,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
  {
    id: "firecrawl",
    name: "Firecrawl",
    provider: "Mendable Inc",
    category: "AI & Research",
    description: "High-fidelity web scraping into LLM-ready markdown with clean DOM extraction.",
    sourceUrl: "https://www.firecrawl.dev",
    iconName: "Globe",
    statusBadge: "Trending",
    capabilitySummary: "URL scrape to markdown, site crawl, documentation ingest.",
    authType: "API Key",
    scopes: ["scrape", "crawl"],
    toolsProvided: ["firecrawl_scrape_page"],
    popularityScore: 94,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
  {
    id: "context7",
    name: "Context7",
    provider: "Context7 AI",
    category: "AI & Research",
    description: "Live documentation grounding, library API reference search, and SDK signatures.",
    sourceUrl: "https://context7.ai",
    iconName: "BookOpen",
    statusBadge: "New",
    capabilitySummary: "Real-time library documentation lookup, function signature verification.",
    authType: "MCP Native",
    scopes: ["search:read"],
    toolsProvided: ["context7_lookup_docs"],
    popularityScore: 89,
    isConnected: true,
    healthState: "HEALTHY",
  },
  {
    id: "exa",
    name: "Exa Neural Search",
    provider: "Exa AI",
    category: "AI & Research",
    description: "Neural web search engine tailored for technical research, papers, and code snippets.",
    sourceUrl: "https://exa.ai",
    iconName: "Search",
    statusBadge: "Trending",
    capabilitySummary: "Semantic search, contents extraction, link discovery.",
    authType: "API Key",
    scopes: ["search"],
    toolsProvided: ["exa_neural_search"],
    popularityScore: 92,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
  {
    id: "consensus",
    name: "Consensus",
    provider: "Consensus AI",
    category: "AI & Research",
    description: "Scientific paper search and evidence aggregation across 200M+ peer-reviewed studies.",
    sourceUrl: "https://consensus.app",
    iconName: "CheckCircle",
    statusBadge: "Trending",
    capabilitySummary: "Evidence synthesis, citation extraction, claim validation.",
    authType: "API Key",
    scopes: ["read"],
    toolsProvided: ["consensus_query_evidence"],
    popularityScore: 90,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
  {
    id: "pubmed",
    name: "PubMed",
    provider: "National Library of Medicine",
    category: "AI & Research",
    description: "Biomedical and life sciences journal citations, abstracts, and full-text links.",
    sourceUrl: "https://pubmed.ncbi.nlm.nih.gov",
    iconName: "FileText",
    statusBadge: "Certified",
    capabilitySummary: "Biomedical literature query, abstract retrieval.",
    authType: "API Key",
    scopes: ["eutils:read"],
    toolsProvided: ["pubmed_search_literature"],
    popularityScore: 88,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
  {
    id: "elicit",
    name: "Elicit",
    provider: "Elicit Inc",
    category: "AI & Research",
    description: "Automated literature review, paper synthesis, and empirical finding extraction.",
    sourceUrl: "https://elicit.com",
    iconName: "BookOpen",
    statusBadge: "Beta",
    capabilitySummary: "Research synthesis, paper table summarization.",
    authType: "API Key",
    scopes: ["read"],
    toolsProvided: ["elicit_search_papers"],
    popularityScore: 86,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
  {
    id: "scite",
    name: "Scite",
    provider: "Scite Inc",
    category: "AI & Research",
    description: "Smart Citations showing whether scientific claims have been supported or contrasted.",
    sourceUrl: "https://scite.ai",
    iconName: "Check",
    statusBadge: "Beta",
    capabilitySummary: "Smart citation query, claim confirmation tracking.",
    authType: "API Key",
    scopes: ["read"],
    toolsProvided: ["scite_check_claim"],
    popularityScore: 83,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
  {
    id: "mermaid_chart",
    name: "Mermaid Chart",
    provider: "Mermaid Chart Inc",
    category: "AI & Research",
    description: "Visual flowcharts, sequence diagrams, ERDs, and state machines generated from text.",
    sourceUrl: "https://www.mermaidchart.com",
    iconName: "GitFork",
    statusBadge: "Trending",
    capabilitySummary: "Diagram syntax compilation, SVG/PNG rendering, diagram validation.",
    authType: "API Key",
    scopes: ["read", "write"],
    toolsProvided: ["mermaid_compile_diagram"],
    popularityScore: 91,
    isConnected: true,
    healthState: "HEALTHY",
  },

  // --- Business & CRM ---
  {
    id: "salesforce",
    name: "Salesforce",
    provider: "Salesforce Inc",
    category: "Business & CRM",
    description: "Enterprise CRM records, account opportunities, customer cases, and custom objects.",
    sourceUrl: "https://www.salesforce.com",
    iconName: "Users",
    statusBadge: "Certified",
    capabilitySummary: "SOQL read query, account metadata search, case escalation tracking.",
    authType: "OAuth 2.0",
    scopes: ["api", "refresh_token"],
    toolsProvided: ["salesforce_query_accounts"],
    popularityScore: 93,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
  {
    id: "hubspot",
    name: "HubSpot",
    provider: "HubSpot Inc",
    category: "Business & CRM",
    description: "Inbound CRM, customer contacts, sales pipelines, and marketing engagement metrics.",
    sourceUrl: "https://www.hubspot.com",
    iconName: "Phone",
    statusBadge: "Certified",
    capabilitySummary: "Contact search, deal pipeline audit, ticket tracking.",
    authType: "OAuth 2.0",
    scopes: ["crm.objects.contacts.read", "crm.objects.deals.read"],
    toolsProvided: ["hubspot_get_deals"],
    popularityScore: 91,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
  {
    id: "clickup",
    name: "ClickUp",
    provider: "ClickUp Inc",
    category: "Business & CRM",
    description: "Workspace task hierarchies, custom task statuses, sprint goals, and checklists.",
    sourceUrl: "https://clickup.com",
    iconName: "CheckSquare",
    statusBadge: "Trending",
    capabilitySummary: "Task filtering, space exploration, status updates.",
    authType: "OAuth 2.0",
    scopes: ["tasks:read"],
    toolsProvided: ["clickup_list_tasks"],
    popularityScore: 90,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
  {
    id: "airtable",
    name: "Airtable",
    provider: "Formagrid Inc",
    category: "Business & CRM",
    description: "Relational low-code spreadsheets, schema bases, records, and linked relations.",
    sourceUrl: "https://airtable.com",
    iconName: "Table",
    statusBadge: "Trending",
    capabilitySummary: "Base schema inspection, record filtering, view pagination.",
    authType: "OAuth 2.0",
    scopes: ["data.records:read", "schema.bases:read"],
    toolsProvided: ["airtable_list_records", "airtable_get_schema"],
    popularityScore: 93,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
  {
    id: "posthog",
    name: "PostHog",
    provider: "PostHog Inc",
    category: "Business & CRM",
    description: "Product analytics, event autocapture, feature flags, and user session trends.",
    sourceUrl: "https://posthog.com",
    iconName: "BarChart",
    statusBadge: "Trending",
    capabilitySummary: "Event trends query, feature flag state check, session duration metrics.",
    authType: "API Key",
    scopes: ["project:read"],
    toolsProvided: ["posthog_get_feature_flags", "posthog_query_events"],
    popularityScore: 94,
    isConnected: true,
    healthState: "HEALTHY",
  },
  {
    id: "intercom",
    name: "Intercom",
    provider: "Intercom Inc",
    category: "Business & CRM",
    description: "Customer conversational support tickets, live messenger triage, and CSAT ratings.",
    sourceUrl: "https://www.intercom.com",
    iconName: "MessageCircle",
    statusBadge: "Certified",
    capabilitySummary: "Conversation search, user sentiment tracking.",
    authType: "OAuth 2.0",
    scopes: ["read"],
    toolsProvided: ["intercom_search_conversations"],
    popularityScore: 87,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
  {
    id: "zoho_crm",
    name: "Zoho CRM",
    provider: "Zoho Corp",
    category: "Business & CRM",
    description: "Leads, pipeline modules, vendor accounts, and customer lifecycle data.",
    sourceUrl: "https://www.zoho.com/crm/",
    iconName: "Briefcase",
    statusBadge: "Certified",
    capabilitySummary: "Module search, lead record inspection.",
    authType: "OAuth 2.0",
    scopes: ["ZohoCRM.modules.READ"],
    toolsProvided: ["zoho_get_leads"],
    popularityScore: 82,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
  {
    id: "semrush",
    name: "Semrush",
    provider: "Semrush Inc",
    category: "Business & CRM",
    description: "Domain SEO authority, keyword rankings, backlink audits, and competitor trends.",
    sourceUrl: "https://www.semrush.com",
    iconName: "TrendingUp",
    statusBadge: "Certified",
    capabilitySummary: "Domain rank query, keyword volume lookup.",
    authType: "API Key",
    scopes: ["read"],
    toolsProvided: ["semrush_audit_domain"],
    popularityScore: 87,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
  {
    id: "zoominfo",
    name: "ZoomInfo",
    provider: "ZoomInfo Technologies",
    category: "Business & CRM",
    description: "B2B contact verification, company technographics, and intent signal metrics.",
    sourceUrl: "https://www.zoominfo.com",
    iconName: "Search",
    statusBadge: "Certified",
    capabilitySummary: "Company technographic profile lookup.",
    authType: "OAuth 2.0",
    scopes: ["read"],
    toolsProvided: ["zoominfo_search_company"],
    popularityScore: 83,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
  {
    id: "indeed",
    name: "Indeed",
    provider: "Indeed Inc",
    category: "Business & CRM",
    description: "Engineering job postings, market talent requirements, and salary benchmarks.",
    sourceUrl: "https://www.indeed.com",
    iconName: "Briefcase",
    statusBadge: "Certified",
    capabilitySummary: "Job search, role requirement indexing.",
    authType: "OAuth 2.0",
    scopes: ["employer:read"],
    toolsProvided: ["indeed_search_roles"],
    popularityScore: 80,
    isConnected: false,
    healthState: "DISCONNECTED",
  },

  // --- Finance & Commerce ---
  {
    id: "stripe",
    name: "Stripe",
    provider: "Stripe Inc",
    category: "Finance & Commerce",
    description: "Payment disputes, invoice states, subscription MRR, and settlement balance audits.",
    sourceUrl: "https://stripe.com",
    iconName: "CreditCard",
    statusBadge: "Trending",
    capabilitySummary: "Dispute read query, invoice status inspection, charge reconciliation.",
    authType: "API Key",
    scopes: ["read_only"],
    toolsProvided: ["stripe_get_disputes", "stripe_read_balance"],
    popularityScore: 98,
    isConnected: true,
    healthState: "HEALTHY",
  },
  {
    id: "shopify",
    name: "Shopify",
    provider: "Shopify Inc",
    category: "Finance & Commerce",
    description: "E-commerce orders, inventory levels, product catalog variants, and fulfillment checks.",
    sourceUrl: "https://www.shopify.com",
    iconName: "ShoppingBag",
    statusBadge: "Trending",
    capabilitySummary: "Order search, inventory check, fulfillment audit.",
    authType: "OAuth 2.0",
    scopes: ["read_orders", "read_products"],
    toolsProvided: ["shopify_get_orders"],
    popularityScore: 92,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
  {
    id: "alpha_vantage",
    name: "Alpha Vantage",
    provider: "Alpha Vantage Inc",
    category: "Finance & Commerce",
    description: "Real-time and historical stock market quotes, forex rates, and crypto indicators.",
    sourceUrl: "https://www.alphavantage.co",
    iconName: "DollarSign",
    statusBadge: "Community",
    capabilitySummary: "Time-series daily quotes, currency exchange rates.",
    authType: "API Key",
    scopes: ["read"],
    toolsProvided: ["alpha_vantage_get_quote"],
    popularityScore: 86,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
  {
    id: "quickbooks",
    name: "QuickBooks Online",
    provider: "Intuit Inc",
    category: "Finance & Commerce",
    description: "General ledger entries, corporate expense tracking, and invoice accounts payable.",
    sourceUrl: "https://quickbooks.intuit.com",
    iconName: "FileCheck2",
    statusBadge: "Certified",
    capabilitySummary: "Ledger account read, invoice balance audit.",
    authType: "OAuth 2.0",
    scopes: ["accounting.read"],
    toolsProvided: ["quickbooks_read_ledger"],
    popularityScore: 84,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
  {
    id: "xero",
    name: "Xero",
    provider: "Xero Ltd",
    category: "Finance & Commerce",
    description: "Cloud accounting, bank feeds, expense claims, and financial balance sheets.",
    sourceUrl: "https://www.xero.com",
    iconName: "BookOpen",
    statusBadge: "Certified",
    capabilitySummary: "Balance sheet extraction, account reconciliation.",
    authType: "OAuth 2.0",
    scopes: ["accounting.reports.read"],
    toolsProvided: ["xero_get_reports"],
    popularityScore: 81,
    isConnected: false,
    healthState: "DISCONNECTED",
  },

  // --- Automation, Media & More ---
  {
    id: "zapier",
    name: "Zapier",
    provider: "Zapier Inc",
    category: "Productivity",
    description: "Multi-app integration zaps, automated task triggers, and webhook pipelines.",
    sourceUrl: "https://zapier.com",
    iconName: "Zap",
    statusBadge: "Trending",
    capabilitySummary: "Zap execution audit, trigger webhook inspection.",
    authType: "OAuth 2.0",
    scopes: ["read"],
    toolsProvided: ["zapier_list_zaps"],
    popularityScore: 93,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
  {
    id: "make",
    name: "Make (Integromat)",
    provider: "Celonis / Make",
    category: "Productivity",
    description: "Visual workflow automation scenarios, webhook payload transformations.",
    sourceUrl: "https://www.make.com",
    iconName: "GitMerge",
    statusBadge: "Trending",
    capabilitySummary: "Scenario status check, execution history audit.",
    authType: "API Key",
    scopes: ["scenarios:read"],
    toolsProvided: ["make_get_scenarios"],
    popularityScore: 89,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
  {
    id: "zoom",
    name: "Zoom Video",
    provider: "Zoom Video Communications",
    category: "Communication",
    description: "Cloud recording transcripts, meeting metadata, and participant presence logs.",
    sourceUrl: "https://zoom.us",
    iconName: "Video",
    statusBadge: "Certified",
    capabilitySummary: "Recording transcript retrieval, meeting audit.",
    authType: "OAuth 2.0",
    scopes: ["recording:read"],
    toolsProvided: ["zoom_get_transcripts"],
    popularityScore: 90,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
  {
    id: "box",
    name: "Box",
    provider: "Box Inc",
    category: "Storage & Documents",
    description: "Enterprise content cloud, compliance folder vaults, and legal holds.",
    sourceUrl: "https://www.box.com",
    iconName: "Box",
    statusBadge: "Certified",
    capabilitySummary: "Folder tree search, file metadata audit.",
    authType: "OAuth 2.0",
    scopes: ["root_readwrite"],
    toolsProvided: ["box_search_files"],
    popularityScore: 85,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
  {
    id: "dropbox",
    name: "Dropbox",
    provider: "Dropbox Inc",
    category: "Storage & Documents",
    description: "Cloud file synchronization, paper documents, and shared team folders.",
    sourceUrl: "https://www.dropbox.com",
    iconName: "Folder",
    statusBadge: "Certified",
    capabilitySummary: "File list search, shared link verification.",
    authType: "OAuth 2.0",
    scopes: ["files.metadata.read"],
    toolsProvided: ["dropbox_search_files"],
    popularityScore: 88,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
  {
    id: "resend",
    name: "Resend",
    provider: "Resend Inc",
    category: "Communication",
    description: "Developer transactional email delivery, domain SPF/DKIM verification, and events.",
    sourceUrl: "https://resend.com",
    iconName: "Mail",
    statusBadge: "Trending",
    capabilitySummary: "Delivery event audit, domain DNS status check.",
    authType: "API Key",
    scopes: ["emails:read"],
    toolsProvided: ["resend_get_email_status"],
    popularityScore: 92,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
  {
    id: "calendly",
    name: "Calendly",
    provider: "Calendly LLC",
    category: "Productivity",
    description: "Appointment scheduling links, scheduled event bookings, and invitee questions.",
    sourceUrl: "https://calendly.com",
    iconName: "Clock",
    statusBadge: "Certified",
    capabilitySummary: "Event booking search, invitee verification.",
    authType: "OAuth 2.0",
    scopes: ["default"],
    toolsProvided: ["calendly_get_events"],
    popularityScore: 88,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
  {
    id: "fireflies",
    name: "Fireflies.ai",
    provider: "Fireflies.ai Inc",
    category: "Productivity",
    description: "AI meeting note extraction, speaker attribution, and conversation topic metrics.",
    sourceUrl: "https://fireflies.ai",
    iconName: "Mic",
    statusBadge: "Trending",
    capabilitySummary: "Transcript search, meeting action item summary.",
    authType: "API Key",
    scopes: ["transcripts:read"],
    toolsProvided: ["fireflies_get_transcripts"],
    popularityScore: 89,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    provider: "ElevenLabs Inc",
    category: "Design & Creative",
    description: "AI voice synthesis, realistic speech models, and audio dubbing telemetry.",
    sourceUrl: "https://elevenlabs.io",
    iconName: "Volume2",
    statusBadge: "Trending",
    capabilitySummary: "Voice library search, audio generation status.",
    authType: "API Key",
    scopes: ["voices:read"],
    toolsProvided: ["elevenlabs_get_voices"],
    popularityScore: 93,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
  {
    id: "descript",
    name: "Descript",
    provider: "Descript Inc",
    category: "Design & Creative",
    description: "Video and podcast audio transcription and multi-track editorial timelines.",
    sourceUrl: "https://www.descript.com",
    iconName: "Video",
    statusBadge: "New",
    capabilitySummary: "Project transcription export, composition search.",
    authType: "OAuth 2.0",
    scopes: ["read"],
    toolsProvided: ["descript_get_transcripts"],
    popularityScore: 82,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
  {
    id: "webflow",
    name: "Webflow",
    provider: "Webflow Inc",
    category: "Design & Creative",
    description: "Visual web design, CMS collections, published site domains, and webhook events.",
    sourceUrl: "https://webflow.com",
    iconName: "Globe",
    statusBadge: "Trending",
    capabilitySummary: "CMS collection item inspection, site publish check.",
    authType: "OAuth 2.0",
    scopes: ["sites:read", "cms:read"],
    toolsProvided: ["webflow_get_collections"],
    popularityScore: 90,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
  {
    id: "wordpress",
    name: "WordPress.com",
    provider: "Automattic Inc",
    category: "Design & Creative",
    description: "Blog posts, REST API publishing, media uploads, and plugin telemetry.",
    sourceUrl: "https://wordpress.com",
    iconName: "FileText",
    statusBadge: "Certified",
    capabilitySummary: "Post search, site status inspection.",
    authType: "OAuth 2.0",
    scopes: ["global"],
    toolsProvided: ["wordpress_get_posts"],
    popularityScore: 87,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
  {
    id: "unsplash",
    name: "Unsplash",
    provider: "Unsplash Inc",
    category: "Design & Creative",
    description: "High-resolution royalty-free imagery, creative photo attribution, and palettes.",
    sourceUrl: "https://unsplash.com",
    iconName: "Image",
    statusBadge: "Community",
    capabilitySummary: "Curated photo search, attribution metadata lookup.",
    authType: "API Key",
    scopes: ["public"],
    toolsProvided: ["unsplash_search_photos"],
    popularityScore: 86,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
  {
    id: "spotify",
    name: "Spotify",
    provider: "Spotify AB",
    category: "Productivity",
    description: "Focus audio playlists, developer background audio, and podcast APIs.",
    sourceUrl: "https://developer.spotify.com",
    iconName: "Music",
    statusBadge: "Community",
    capabilitySummary: "Playlist query, audio metadata search.",
    authType: "OAuth 2.0",
    scopes: ["user-read-playback-state"],
    toolsProvided: ["spotify_get_playlist"],
    popularityScore: 83,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
  {
    id: "strava",
    name: "Strava",
    provider: "Strava Inc",
    category: "Productivity",
    description: "Athletic wellness metrics and team physical energy telemetry.",
    sourceUrl: "https://www.strava.com",
    iconName: "Activity",
    statusBadge: "Community",
    capabilitySummary: "Activity stream read.",
    authType: "OAuth 2.0",
    scopes: ["activity:read"],
    toolsProvided: ["strava_get_activities"],
    popularityScore: 78,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
  {
    id: "uber",
    name: "Uber Enterprise",
    provider: "Uber Technologies",
    category: "Productivity",
    description: "Corporate travel, ride receipts, and executive transit itineraries.",
    sourceUrl: "https://developer.uber.com",
    iconName: "MapPin",
    statusBadge: "Community",
    capabilitySummary: "Receipt search, transit log lookup.",
    authType: "OAuth 2.0",
    scopes: ["history"],
    toolsProvided: ["uber_get_trips"],
    popularityScore: 75,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
  {
    id: "wix",
    name: "Wix",
    provider: "Wix.com Ltd",
    category: "Design & Creative",
    description: "Website builder pages, store products, and domain settings.",
    sourceUrl: "https://www.wix.com",
    iconName: "Layout",
    statusBadge: "Certified",
    capabilitySummary: "Site pages inspection.",
    authType: "OAuth 2.0",
    scopes: ["read"],
    toolsProvided: ["wix_get_pages"],
    popularityScore: 81,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
  {
    id: "trello",
    name: "Trello",
    provider: "Atlassian",
    category: "Productivity",
    description: "Kanban boards, cards, checklists, and team collaboration labels.",
    sourceUrl: "https://trello.com",
    iconName: "Trello",
    statusBadge: "Certified",
    capabilitySummary: "Board cards query, checklist progress audit.",
    authType: "OAuth 2.0",
    scopes: ["read"],
    toolsProvided: ["trello_get_cards"],
    popularityScore: 87,
    isConnected: false,
    healthState: "DISCONNECTED",
  },
];
